### ISSUE TITLE
Conflicts with gatsby projects

### ISSUE THREAD

**Issue by CeoFred** [cristobal-io/mortgage-calculator#4]
While trying to generate a production build, it fails. 
This is the error message on every operating system.

success run page queries - 0.244 s — 10/10 58.17 queries/second
⠏ Building static HTML for pages
/home/james/IdeaProjects/ibcscorp/primeagile-ui/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
       throw ex;
       ^
Error: Cannot find module 'lodash/object/defaults'
   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
   at Function.resolve (internal/modules/cjs/helpers.js:32:19)
   at isExternal (/home/james/IdeaProjects/ibcscorp/primeagile-ui/node_modules/gatsby/dist/utils/webpack.config.js:505:31)
   at config.externals (/home/james/IdeaProjects/ibcscorp/primeagile-ui/node_modules/gatsby/dist/utils/webpack.config.js:516:24)
   at handleExternals (/home/james/IdeaProjects/ibcscorp/primeagile-ui/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:78:17)
   at next (/home/james/IdeaProjects/ibcscorp/primeagile-ui/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:66:9)
   at handleExternals (/home/james/IdeaProjects/ibcscorp/primeagile-ui/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:71:7)
   at /home/james/IdeaProjects/ibcscorp/primeagile-ui/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:101:5
   at hooks.beforeResolve.callAsync (/home/james/IdeaProjects/ibcscorp/primeagile-ui/node_modules/webpack/lib/NormalModuleFactory.js:400:5)
   at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/james/IdeaProjects/ibcscorp/primeagile-ui/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
   at NormalModuleFactory.create (/home/james/IdeaProjects/ibcscorp/primeagile-ui/node_modules/webpack/lib/NormalModuleFactory.js:381:28)
   at semaphore.acquire (/home/james/IdeaProjects/ibcscorp/primeagile-ui/node_modules/webpack/lib/Compilation.js:897:14)
   at Semaphore.acquire (/home/james/IdeaProjects/ibcscorp/primeagile-ui/node_modules/webpack/lib/util/Semaphore.js:29:4)
   at asyncLib.forEach (/home/james/IdeaProjects/ibcscorp/primeagile-ui/node_modules/webpack/lib/Compilation.js:895:15)
   at arrayEach (/home/james/IdeaProjects/ibcscorp/primeagile-ui/node_modules/neo-async/async.js:2405:9)
   at Object.each (/home/james/IdeaProjects/ibcscorp/primeagile-ui/node_modules/neo-async/async.js:2846:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! primagile-ui@0.0.1 build: gatsby build
npm ERR! Exit status 7
npm ERR!

**Comment by cristobal-io** [comment]
I have not tried to integrate it with Gatsby.

If you find a bug and you want to submit a PR, I'll be happy to review and add it to the package.

I'll close this ticket.

Thanks for using the package.
